package com.example.tts.service;

import com.example.tts.entity.User;
import com.example.tts.repository.SpeechHistoryRepository;
import com.example.tts.repository.UserRepository;
import org.springframework.stereotype.Service;

import java.lang.management.ManagementFactory;
import java.util.*;

@Service
public class AnalyticsService {

    private final SpeechHistoryRepository historyRepository;
    private final UserRepository userRepository;
    private final VoiceCatalogService voiceCatalogService;

    public AnalyticsService(SpeechHistoryRepository historyRepository,
                            UserRepository userRepository,
                            VoiceCatalogService voiceCatalogService) {
        this.historyRepository = historyRepository;
        this.userRepository = userRepository;
        this.voiceCatalogService = voiceCatalogService;
    }

    /**
     * System-wide Analytics: Exclusively for Administrators
     */
    public Map<String, Object> getSystemAnalytics() {
        long totalGenerations = historyRepository.getTotalGenerations();
        long totalCharacters = historyRepository.getTotalCharactersConverted();
        long totalUsers = userRepository.count();

        List<Object[]> rawLanguages = historyRepository.getPopularLanguages();
        List<Map<String, Object>> languageStats = new ArrayList<>();
        for (Object[] row : rawLanguages) {
            languageStats.add(Map.of("language", row[0], "count", row[1]));
        }

        List<Object[]> rawVoices = historyRepository.getPopularVoices();
        List<Map<String, Object>> voiceStats = new ArrayList<>();
        for (Object[] row : rawVoices) {
            voiceStats.add(Map.of("voice", row[0], "count", row[1]));
        }

        long uptimeSeconds = ManagementFactory.getRuntimeMXBean().getUptime() / 1000;

        return Map.of(
                "totalUsers", totalUsers,
                "totalGenerations", totalGenerations,
                "totalCharactersConverted", totalCharacters,
                "popularLanguages", languageStats,
                "popularVoices", voiceStats,
                "supportedLanguagesCount", voiceCatalogService.getSupportedLanguages().size(),
                "supportedVoicesCount", voiceCatalogService.getAllVoices().size(),
                "uptimeSeconds", uptimeSeconds
        );
    }

    /**
     * User-Specific Analytics: Only contains data generated by the logged-in user
     */
    public Map<String, Object> getUserAnalytics(User user) {
        if (user == null) {
            return Map.of(
                    "totalGenerations", 0L,
                    "totalCharactersConverted", 0L,
                    "totalWordsConverted", 0L,
                    "popularLanguages", List.of(),
                    "popularVoices", List.of()
            );
        }

        long totalGenerations = historyRepository.countByUser(user);
        long totalCharacters = historyRepository.getTotalCharactersByUser(user);
        long totalWords = historyRepository.getTotalWordsByUser(user);

        List<Object[]> rawLanguages = historyRepository.getPopularLanguagesByUser(user);
        List<Map<String, Object>> languageStats = new ArrayList<>();
        for (Object[] row : rawLanguages) {
            languageStats.add(Map.of("language", row[0], "count", row[1]));
        }

        List<Object[]> rawVoices = historyRepository.getPopularVoicesByUser(user);
        List<Map<String, Object>> voiceStats = new ArrayList<>();
        for (Object[] row : rawVoices) {
            voiceStats.add(Map.of("voice", row[0], "count", row[1]));
        }

        Map<String, Object> result = new HashMap<>();
        result.put("totalGenerations", totalGenerations);
        result.put("totalCharactersConverted", totalCharacters);
        result.put("totalWordsConverted", totalWords);
        result.put("popularLanguages", languageStats);
        result.put("popularVoices", voiceStats);
        result.put("userEmail", user.getEmail());
        result.put("userName", user.getName());
        result.put("averageCharsPerGeneration", totalGenerations > 0 ? (totalCharacters / totalGenerations) : 0L);

        return result;
    }
}
